en:
  domain: vec.io
  session_key: _vec_io_session_mem_cache_secure

  memcache:
    servers:
      - 127.0.0.1
    options:
      namespace: _vec_io_cache_dalli
      expires_in: <%= 1.day %>
      compress: true

  html:
    title: VEC.IO
    keywords: Vector,Matrix,Graphics,OpenGL,CV,Computer Vision,FFmpeg,Android,Ruby,Rails,Haskell,Java,C
    description: Strive to formulate elegant code, simple design and friendly machine.

  email:
    default: root@vec.io
    smtp:
      host: smtp.vec.io
      port: 25
      user_name: root@vec.io
      password: vec.io

  socials:
    twitter: cedricfung
    github: vecio
    google_plus: 115530211243475994661
    facebook: cedric.vec.io

  google_analytics:
    account: UA-5406207-6
    domain: vec.io
